//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MassDostTotal
    {
        public int IdT { get; set; }
        public Nullable<decimal> Massa { get; set; }
        public Nullable<int> IdNeft { get; set; }
        public Nullable<int> IdZayTotal { get; set; }
    
        public virtual Nefteproduct Nefteproduct { get; set; }
        public virtual ZayTotal ZayTotal { get; set; }
    }
}
