//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OstatkiDelete
    {
        public int ID { get; set; }
        public Nullable<int> Sklad { get; set; }
        public Nullable<int> Nefteprod { get; set; }
        public Nullable<decimal> V { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> DateSozd { get; set; }
        public string UserSozd { get; set; }
        public Nullable<System.DateTime> DateDelete { get; set; }
        public string UserDelete { get; set; }
    
        public virtual Nefteproduct Nefteproduct { get; set; }
        public virtual Sklad Sklad1 { get; set; }
    }
}
