//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableZayTotal
    {
        public int id { get; set; }
        public int idZayTotal { get; set; }
        public Nullable<int> idFilial { get; set; }
        public Nullable<int> idNeft { get; set; }
        public Nullable<decimal> Potrebnost { get; set; }
        public Nullable<decimal> Oststok { get; set; }
        public Nullable<decimal> DostavkaFact { get; set; }
        public Nullable<decimal> NalichSkladHran { get; set; }
        public Nullable<decimal> PlanV { get; set; }
        public string Primech { get; set; }
        public string UserModific { get; set; }
        public Nullable<System.DateTime> DateModific { get; set; }
    
        public virtual Nefteproduct Nefteproduct { get; set; }
        public virtual Organization Organization { get; set; }
        public virtual ZayTotal ZayTotal { get; set; }
        public virtual Sklad Sklad { get; set; }
    }
}
