//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TableDog
    {
        public int IdTD { get; set; }
        public Nullable<System.DateTime> DateMonth { get; set; }
        public Nullable<int> IdDog { get; set; }
        public Nullable<int> IdNeft { get; set; }
        public Nullable<decimal> Massa { get; set; }
        public string Primech { get; set; }
        public string UserModific { get; set; }
        public Nullable<System.DateTime> DateModific { get; set; }
    
        public virtual Dogovory Dogovory { get; set; }
        public virtual Nefteproduct Nefteproduct { get; set; }
    }
}
