//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserRoles
    {
        public int IdUR { get; set; }
        public int IdUser { get; set; }
        public Nullable<int> idRole { get; set; }
    
        public virtual Autorize Autorize { get; set; }
        public virtual Roles Roles { get; set; }
    }
}
