//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RecordOil.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Users()
        {
            this.Autorize = new HashSet<Autorize>();
        }
    
        public int IdUserrs { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string MidleName { get; set; }
        public Nullable<int> idFil { get; set; }
        public string UserModific { get; set; }
        public Nullable<System.DateTime> DateModific { get; set; }
        public Nullable<int> idDolj { get; set; }
        public string Phone { get; set; }
        public Nullable<int> Podpisant { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Autorize> Autorize { get; set; }
        public virtual Doljnost Doljnost { get; set; }
        public virtual Organization Organization { get; set; }
    }
}
